type: object
properties:
  imageId:
    type: string
  imageName:
    type: string
  layerId:
    type: string
  vulnerability:
    $ref: '#/components/schemas/DeliverySecurityVulnerability'
  feature:
    $ref: '#/components/schemas/DeliverySecurityFeature'
  severity:
    type: string
