type: object
properties:
  id:
    type: string
    readOnly: true
  imageDigest:
    type: object
    additionalProperties:
      type: string
      description: property既是服务名称
  ancestryInfo:
    type: object
    additionalProperties:
      type: string
      description: property既是服务名称
  createdAt:
    type: integer
