type: object
properties:
  id:
    type: string
    readOnly: true
  fileContentList:
    type: object
    additionalProperties:
      type: array
      items:
        type: array
        items:
          type: string