type: object
description: "产品全局变量"
properties:
  key:
    type: string
    description: '变量名称 [a-z][a-z0-9A-Z_\-]+'
  defaultValue:
    type: string
    description: 变量默认值 
  secured:
    type: boolean
    description: 是否加密