type: object
properties:
  name:
    type: string
    description: 产品名称
  desc:
    type: string
    description: 产品描述
  teams:
    type: array
    items:
      $ref: "#/components/schemas/TeamLite"
  publisher:
    type: array
    items:
      $ref: "#/components/schemas/UserLite"