openapi: 3.0.0
servers:
  - description: Poetry API Auto Mocking
    url: 'http://poetry-api.dev.8slan.com'
info:
  version: 1.0.0
  title: Poetry api
  description: 'Poetry api协议, 分页协议参考https://docs.gitlab.com/ee/api/#pagination-link-header'
