parameters:
  - name: configId
    in: path
    description: 交付配置文件信息ID
    required: true
    schema:
      type: string
delete:
  security:
    - ApiKeyAuth: []
    - ApiRootKeyAuth: []
  tags:
    - DeliveryCenter
  summary: 删除配置文件信息
  responses:
    '200':
      description: 删除成功